# Generated by Django 3.2.7 on 2021-09-17 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0003_auto_20210916_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('-created_date',)},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-created_date',)},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
