# Generated by Django 3.2.7 on 2021-09-17 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_account_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to='wallet.account'),
        ),
    ]
